version: '3'
services:
  api: 
    image: cbapi 
    build:
      context: ./
      dockerfile: Dockerfile.api
    restart: unless-stopped
    ports:
      - "9004:9004"

  frontend:
    image: cbfrontend
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
     - ./mongodata:/data/db
    ports:
      - "27017:27017"
